### ISSUE TITLE
No "exports" main defined

### ISSUE THREAD

**Issue by mailok** [dotcore64/i18next-fetch-backend#193]
I was trying to use the library but the `package.json` doesn't have any `main` defined, and that gives me an error. Do you know any fix for this kind of error?

```
Error: No "exports" main defined in /Users/angel/WebstormProjects/lazy-app/node_modules/i18next-fetch-backend/package.json
    at new NodeError (node:internal/errors:371:5)
    at throwExportsNotFound (node:internal/modules/esm/resolve:429:9)
    at packageExportsResolve (node:internal/modules/esm/resolve:650:7)
    at resolveExports (node:internal/modules/cjs/loader:482:36)
    at Function.Module._findPath (node:internal/modules/cjs/loader:522:31)
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:919:27)
    at Function.Module._load (node:internal/modules/cjs/loader:778:27)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
    at Object.<anonymous> (/Users/angel/WebstormProjects/lazy-app/app/utils/language.ts:6:19)
    at Module._compile (node:internal/modules/cjs/loader:1097:14)
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1151:10)
    at Module.load (node:internal/modules/cjs/loader:975:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:999:19)
    at require (node:internal/modules/cjs/helpers:102:18)
```

**Comment by perrin4869** [comment]
Starting from v5, this module doesn't support loading via `commonjs`. You could use v4, which is the same functionality, or migrate your project to use `esm`

**Comment by mailok** [comment]
Thank you very much for your response.
I tried with version 4, but for some reason I can't get it to work, the library import gives me an error.

I tried this form:
`import Fetch from 'i18next-fetch-backend';`
And with this one:
`const Fetch = require('i18next-fetch-backend');`

But I always get the same error:
```
ReferenceError: fetch is not defined

    at Object.<anonymous> (/Users/angel/WebstormProjects/lazy-app/node_modules/i18next-fetch-backend/src/index.js:8:3)
    at Object.<anonymous> (/Users/angel/WebstormProjects/lazy-app/app/utils/language.ts:8:15)
```

_In this file and in this line the import is made_:`language.ts:8:15`


I am doing an application with [remix](https://remix.run/), and I am developing the e2e tests with [Playwright](https://playwright.dev/). My application has internationalization, and I am trying in the e2e environment to have [i18next](https://www.i18next.com/) initialized with the same language that the application has when running the e2e test.

I tried using the [i18next-http-backend](https://github.com/i18next/i18next-http-backend) plugin, but was unsuccessful.

The last thing I tried, was to use **isomorphic-fetch** to do the language resource request on my own. But for some mysterious reason, i18next has no use for it, because it doesn't work and doesn't give me any errors 😩.

```
const source = await fetch(`http://localhost:3000/locales/${languageDetected}.json`).then((response) =>
        response.json(),
      );
      await i18n.use(initReactI18next).init(defaultOptions);
      i18n.addResources(languageDetected, defaultNamespace, source);
```

**Comment by perrin4869** [comment]
@mailok Oh, yeah I see why using `v4` is crashing. Ideally you will polyfill `fetch` using `isomorphic-fetch` or `cross-fetch` before loading this module, but it shouldn't crash if it is not defined.
I pushed out `v4.1.3`, can you try again using `isomorphic-fetch`?

**Comment by mailok** [comment]
Hi. I tried what you told me and the error disappeared. But for some strange reason, I18n didn't translate anything for me, it's as if I didn't have any resources to do the translation.

Anyway, I kept experimenting with making the request on my own, and managed to make it work this way:

```
case 'E2e':
 const response = await fetch(`http://localhost:3000/locales/${languageDetected}.json`);
 const source = await response.json();
 defaultOptions.resources = {
      [languageDetected]: {
        translation: source,
      },
 };
 await i18n.use(initReactI18next).init(defaultOptions);
 break;
```
